#!/bin/bash
set -e

case "$1" in
    purge|remove)
        # Clean up autologin config if exists
        rm -f /etc/lightdm/lightdm.conf.d/50-wlanpi-autologin.conf
        
        # Reload systemd
        systemctl daemon-reload >/dev/null 2>&1 || true
        ;;
esac

#DEBHELPER#

exit 0
